apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/kashyaphebbar/autonomous-enterprise-ai-os
    newTag: staging
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: api-deployment-patch.yaml
  - path: worker-deployment-patch.yaml
