apiVersion: v1
kind: ConfigMap
metadata:
  name: aeai-config
  namespace: aeai-os
data:
  AEAI_ENV: "local"
  AEAI_AUTH_ENABLED: "false"
  AEAI_AUTH_MODE: "local"
  AEAI_TRACE_EXPORTER: "none"
  AEAI_OTEL_EXPORTER_OTLP_ENDPOINT: ""
