apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../..
images:
  - name: ghcr.io/kashyaphebbar/autonomous-enterprise-ai-os
    newTag: production
patchesStrategicMerge:
  - configmap-patch.yaml
  - secret-patch.yaml
  - api-deployment-patch.yaml
  - worker-deployment-patch.yaml
