apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
  - service-monitor.yaml
  - prometheus-rules.yaml
  - external-secret.yaml
images:
  - name: ghcr.io/kashyaphebbar/autonomous-enterprise-ai-os
    newTag: production
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - path: delete-postgres-deployment.yaml
  - path: delete-postgres-service.yaml
  - path: delete-redis-deployment.yaml
  - path: delete-redis-service.yaml
  - path: delete-minio-deployment.yaml
  - path: delete-minio-service.yaml
  - path: api-deployment-patch.yaml
  - path: worker-deployment-patch.yaml
