from __future__ import annotations

import argparse
import json
import shutil
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "artifacts" / "release" / "v1.0"

PACKAGE_FILES = [
    ("README.md", "README.md"),
    ("docs/portfolio-architecture.md", "docs/portfolio-architecture.md"),
    ("docs/release/v1.0-checklist.md", "docs/release/v1.0-checklist.md"),
    ("docs/release/v1.0-release-notes.md", "docs/release/v1.0-release-notes.md"),
    ("docs/release/v1.0-demo-walkthrough.md", "docs/release/v1.0-demo-walkthrough.md"),
    ("docs/release/v1.0-demo-assets.md", "docs/release/v1.0-demo-assets.md"),
    ("deploy/kubernetes/README.md", "deploy/kubernetes/README.md"),
    ("deploy/cloud/aws/README.md", "deploy/cloud/aws/README.md"),
    ("examples/procurement_demo.csv", "examples/procurement_demo.csv"),
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the v1.0 portfolio demo package.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where the package should be written.",
    )
    args = parser.parse_args(argv)

    manifest = build_release_package(args.output_dir)
    print(f"Release package written: {args.output_dir}")
    print(f"Manifest: {manifest}")
    return 0


def build_release_package(output_dir: Path = DEFAULT_OUTPUT_DIR) -> Path:
    package_root = output_dir.resolve()
    package_root.mkdir(parents=True, exist_ok=True)

    copied_files: list[str] = []
    for source, destination in PACKAGE_FILES:
        source_path = ROOT / source
        destination_path = package_root / destination
        if not source_path.exists():
            raise FileNotFoundError(f"Release package source is missing: {source}")
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)
        copied_files.append(destination)

    package_readme = package_root / "DEMO_PACKAGE.md"
    package_readme.write_text(_package_readme(), encoding="utf-8")
    copied_files.append("DEMO_PACKAGE.md")

    manifest_path = package_root / "release-package-manifest.json"
    manifest = {
        "package": "autonomous-enterprise-ai-os-v1.0-demo",
        "created_at": datetime.now(UTC).isoformat(),
        "source_root": str(ROOT),
        "files": sorted(copied_files),
        "validation_commands": [
            "make lint",
            "make test",
            "make smoke",
            "make demo",
            "make k8s-validate",
            "make cloud-validate",
            "make release-package",
        ],
        "ui_links": [
            "http://127.0.0.1:8000/app",
            "http://127.0.0.1:8000/app/artifacts",
            "http://127.0.0.1:8000/app/admin",
            "http://127.0.0.1:8000/run-inspector/runs/{run_id}",
            "http://127.0.0.1:8000/docs",
            "http://127.0.0.1:8000/metrics",
        ],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest_path


def _package_readme() -> str:
    return """# Autonomous Enterprise AI OS v1.0 Demo Package

This folder is generated by `make release-package`.

Recommended reviewer path:

1. Read `README.md`.
2. Read `docs/portfolio-architecture.md`.
3. Follow `docs/release/v1.0-demo-walkthrough.md`.
4. Use `docs/release/v1.0-demo-assets.md` for screenshot or short clip capture.
5. Use `docs/release/v1.0-checklist.md` and `docs/release/v1.0-release-notes.md` for launch review.

The included sample dataset is `examples/procurement_demo.csv`.
"""


if __name__ == "__main__":
    raise SystemExit(main())
